theme = "hyde"
baseURL = "https://harvardgwe.com/"
languageCode = "en-us"
title = "Harvard Grad Women in Econ"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#googleAnalytics = ""
footnotereturnlinkcontents = "↩"

[params]
  themeColor = "theme-base-08"
  description = "Working towards a more inclusive economics environment"
  #authorimage = "/img/gwe2.png"
  #copyright = "Harvard GWE"
  
## Main Menu
[[menu.main]]
    name = "FAQs"
    identifier = "faqs"
    weight = 100
    url = "/faqs/" 
[[menu.main]]
    name = "Events"
    weight = 200
    identifier = "events"
    url = "/events/"     
[[menu.main]]
    name = "Team"
    identifier = "team"
    weight = 300
    url = "/team/"
[[menu.main]]
    name = "Get Involved"
    identifier = "get-involved"
    weight = 400
    url = "/get-involved/"    