theme = "hyde"
baseURL = "https://alex-builds-a-draft-website.netlify.com/"
languageCode = "en-us"
title = "Harvard Grad Women in Econ"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#googleAnalytics = ""
footnotereturnlinkcontents = "↩"

[params]
  themeColor = "theme-base-08"
  description = "Working towards a more inclusive economics"
  #authorimage = "/img/gwe2.png"
  #copyright = "Harvard GWE"
  
## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "FAQs"
    identifier = "faqs"
    weight = 200
    url = "/faqs/" 
#[[menu.main]]
#    name = "Events1"
#    weight = 300
#    identifier = "posts"
#    url = "/posts/"
[[menu.main]]
    name = "Events"
    weight = 300
    identifier = "events"
    url = "/events/"     
[[menu.main]]
    name = "Team"
    identifier = "team"
    weight = 400
    url = "/team/"
[[menu.main]]
    name = "Get Involved"
    identifier = "get-involved"
    weight = 500
    url = "/get-involved/"    